extends: "spectral:oas"
rules:
  # Disable oas3-schema for path item $ref - this is a known Spectral issue
  # with OpenAPI 3.1.0 where external $ref in path items causes false
  # "unevaluated properties" errors. The spec is validated by Redocly.
  oas3-schema: off